default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true

development:
  <<: *default
  compile: false
  extract_css: false
  check_yarn_integrity: false

test:
  <<: *default
  compile: false
  public_output_path: packs-test

production:
  <<: *default
  compile: false
  extract_css: false
